# SACH_LINK_SACH_VERTRAG_RIS.sql

drop table T_LVM_MART.SACH_LINK_SACH_VERTRAG_RIS;
drop table T_LVM_MART_EXT.EXT_SACH_LINK_SACH_VERTRAG_RIS;
drop table T_LVM_MART_WORK.TR_SACH_LINK_SACH_VERTRAG_RIS;
drop table T_LVM_MART_WORK.LD_SACH_LINK_SACH_VERTRAG_RIS;

CREATE MULTISET TABLE T_LVM_MART_EXT.EXT_SACH_LINK_SACH_VERTRAG_RIS ,FALLBACK ,
NO BEFORE JOURNAL,
NO AFTER JOURNAL,
CHECKSUM = DEFAULT,
DEFAULT MERGEBLOCKRATIO,
MAP = TD_MAP1
(
PRIMARY_KEY DECIMAl(20, 0),
SOURCE_TABLE VARCHAR(50) DEFAULT 'HUB_VERTRAG and HUB RIS',
FOREIGN_KEY_VERTRAG DECIMAl(20, 0) NOT NULL,
FOREIGN_KEY_RIS DECIMAl(20, 0) NOT NULL
)
NO PRIMARY INDEX;

CREATE MULTISET TABLE T_LVM_MART_WORK.TR_SACH_LINK_SACH_VERTRAG_RIS ,FALLBACK ,
NO BEFORE JOURNAL,
NO AFTER JOURNAL,
CHECKSUM = DEFAULT,
DEFAULT MERGEBLOCKRATIO,
MAP = TD_MAP1
(
PRIMARY_KEY DECIMAl(20, 0),
SOURCE_TABLE VARCHAR(50),
FOREIGN_KEY_VERTRAG DECIMAl(20, 0) NOT NULL,
FOREIGN_KEY_RIS DECIMAl(20, 0) NOT NULL
)
PRIMARY INDEX ( PRIMARY_KEY );

CREATE MULTISET TABLE T_LVM_MART_WORK.LD_SACH_LINK_SACH_VERTRAG_RIS ,FALLBACK ,
NO BEFORE JOURNAL,
NO AFTER JOURNAL,
CHECKSUM = DEFAULT,
DEFAULT MERGEBLOCKRATIO,
MAP = TD_MAP1
(
PRIMARY_KEY DECIMAl(20, 0) NOT NULL,
SOURCE_TABLE VARCHAR(50),
FOREIGN_KEY_VERTRAG DECIMAl(20, 0) NOT NULL,
FOREIGN_KEY_RIS DECIMAl(20, 0) NOT NULL,
LOADDATE TIMESTAMP(6) NOT NULL
)
PRIMARY INDEX ( PRIMARY_KEY );

CREATE MULTISET TABLE T_LVM_MART.SACH_LINK_SACH_VERTRAG_RIS ,FALLBACK ,
NO BEFORE JOURNAL,
NO AFTER JOURNAL,
CHECKSUM = DEFAULT,
DEFAULT MERGEBLOCKRATIO,
MAP = TD_MAP1
(
PRIMARY_KEY DECIMAl(20, 0) NOT NULL,
SOURCE_TABLE VARCHAR(50),
FOREIGN_KEY_VERTRAG DECIMAl(20, 0) NOT NULL,
FOREIGN_KEY_RIS DECIMAl(20, 0) NOT NULL,
LOADDATE TIMESTAMP(6) NOT NULL
)
PRIMARY INDEX ( PRIMARY_KEY ,LOADDATE );