# SACH_SAT_SACH_VERTRAG_BEIT.sql

drop table T_LVM_MART.SACH_SAT_SACH_VERTRAG_BEIT;
drop table T_LVM_MART_EXT.EXT_SACH_SAT_SACH_VERTRAG_BEIT;
drop table T_LVM_MART_WORK.TR_SACH_SAT_SACH_VERTRAG_BEIT;
drop table T_LVM_MART_WORK.LD_SACH_SAT_SACH_VERTRAG_BEIT;

CREATE MULTISET TABLE T_LVM_MART_EXT.EXT_SACH_SAT_SACH_VERTRAG_BEIT ,FALLBACK ,
NO BEFORE JOURNAL,
NO AFTER JOURNAL,
CHECKSUM = DEFAULT,
DEFAULT MERGEBLOCKRATIO,
MAP = TD_MAP1
(
PRIMARY_KEY DECIMAL(20,0) NOT NULL,
VSNR VARCHAR(50) CHARACTER SET LATIN CASESPECIFIC NOT NULL,
VG_SICHT_ZP TIMESTAMP(6) NOT NULL,
GUELTIG_VON_ZP TIMESTAMP(6) NOT NULL,
AS_LFD_NR SMALLINT,
VS_BEDINGUNG_GEN SMALLINT,
VERTRAGSART_SCHL SMALLINT,
VERTRAG_STATUS_SCHL SMALLINT,
VG_GUELT_BEG_DAT DATE FORMAT 'YY/MM/DD',
ARBEITSSCHRITT_SCHL SMALLINT,
VS_BEDINGUNG_FAM SMALLINT,
HAUPTFAELLIGKEIT_MONAT SMALLINT,
HAUPTFAELLIGKEIT_TAG SMALLINT,
BEIT_GEM_ZW_BRUTTO DECIMAL(14,2),
BEIT_GEM_ZW_NETTO DECIMAL(14,2),
EINWILLIGUNSERKL_ART SMALLINT,
IDENTIFIZIERUNG_KTXT VARCHAR(50) CHARACTER SET LATIN CASESPECIFIC,
J_BEIT_BRUTTO DECIMAL(14,2),
J_BEIT_NETTO DECIMAL(14,2),
J_BEIT_NETTO_O_ZW DECIMAL(14,2),
VN_PA_REF_NR VARCHAR(50) CHARACTER SET LATIN CASESPECIFIC,
PROD_LINIE SMALLINT,
VTR_SB_BETR SMALLINT,
VTR_SB_PROZ SMALLINT,
STORNIERER SMALLINT,
TARIFMERKMAL SMALLINT,
VS_BEGINN_DAT DATE FORMAT 'YY/MM/DD',
VS_ENDE_DAT DATE FORMAT 'YY/MM/DD',
VN_ART_SCHL SMALLINT,
VS_STEUER_BETR DECIMAL(14,2),
VS_STEUER_GEM_ZW DECIMAL(14,2),
VS_ZWEIG SMALLINT,
ZW SMALLINT,
GUELTIG_BIS_ZP TIMESTAMP(6) NOT NULL,
VERARBEITUNG_ZP TIMESTAMP(6) NOT NULL
)
NO PRIMARY INDEX;
CREATE MULTISET TABLE T_LVM_MART_WORK.TR_SACH_SAT_SACH_VERTRAG_BEIT ,FALLBACK ,
NO BEFORE JOURNAL,
NO AFTER JOURNAL,
CHECKSUM = DEFAULT,
DEFAULT MERGEBLOCKRATIO,
MAP = TD_MAP1
(
HUB_VERTRAG_HASH_KEY DECIMAL(20,0) NOT NULL,
LOAD_DATE TIMESTAMP(6),
LOAD_END_DATE TIMESTAMP(6),
RECORD_SOURCE VARCHAR(50),
HASHDIFF DECIMAL(20, 0),
HAUPTFAELLIGKEIT_MONAT SMALLINT,
HAUPTFAELLIGKEIT_TAG SMALLINT,
BEIT_GEM_ZW_BRUTTO DECIMAL(14,2),
BEIT_GEM_ZW_NETTO DECIMAL(14,2),
J_BEIT_BRUTTO DECIMAL(14,2),
J_BEIT_NETTO DECIMAL(14,2),
J_BEIT_NETTO_O_ZW DECIMAL(14,2),
VTR_SB_BETR SMALLINT,
VTR_SB_PROZ SMALLINT,
VS_STEUER_BETR DECIMAL(14,2),
VS_STEUER_GEM_ZW DECIMAL(14,2)
)
PRIMARY INDEX( HUB_VERTRAG_HASH_KEY, LOAD_DATE );
CREATE MULTISET TABLE T_LVM_MART_WORK.LD_SACH_SAT_SACH_VERTRAG_BEIT ,FALLBACK ,
NO BEFORE JOURNAL,
NO AFTER JOURNAL,
CHECKSUM = DEFAULT,
DEFAULT MERGEBLOCKRATIO,
MAP = TD_MAP1
(
HUB_VERTRAG_HASH_KEY DECIMAL(20,0) NOT NULL,
LOAD_DATE TIMESTAMP(6),
LOAD_END_DATE TIMESTAMP(6),
RECORD_SOURCE VARCHAR(50),
HASHDIFF DECIMAL(20, 0),
HAUPTFAELLIGKEIT_MONAT SMALLINT,
HAUPTFAELLIGKEIT_TAG SMALLINT,
BEIT_GEM_ZW_BRUTTO DECIMAL(14,2),
BEIT_GEM_ZW_NETTO DECIMAL(14,2),
J_BEIT_BRUTTO DECIMAL(14,2),
J_BEIT_NETTO DECIMAL(14,2),
J_BEIT_NETTO_O_ZW DECIMAL(14,2),
VTR_SB_BETR SMALLINT,
VTR_SB_PROZ SMALLINT,
VS_STEUER_BETR DECIMAL(14,2),
VS_STEUER_GEM_ZW DECIMAL(14,2),
VERARBEITUNG_ZP TIMESTAMP(6) NOT NULL
)
PRIMARY INDEX( HUB_VERTRAG_HASH_KEY, LOAD_DATE );
CREATE MULTISET TABLE T_LVM_MART.SACH_SAT_SACH_VERTRAG_BEIT ,FALLBACK ,
NO BEFORE JOURNAL,
NO AFTER JOURNAL,
CHECKSUM = DEFAULT,
DEFAULT MERGEBLOCKRATIO,
MAP = TD_MAP1
(
HUB_VERTRAG_HASH_KEY DECIMAL(20,0) NOT NULL,
LOAD_DATE TIMESTAMP(6),
LOAD_END_DATE TIMESTAMP(6),
RECORD_SOURCE VARCHAR(50),
HASHDIFF DECIMAL(20, 0),
HAUPTFAELLIGKEIT_MONAT SMALLINT,
HAUPTFAELLIGKEIT_TAG SMALLINT,
BEIT_GEM_ZW_BRUTTO DECIMAL(14,2),
BEIT_GEM_ZW_NETTO DECIMAL(14,2),
J_BEIT_BRUTTO DECIMAL(14,2),
J_BEIT_NETTO DECIMAL(14,2),
J_BEIT_NETTO_O_ZW DECIMAL(14,2),
VTR_SB_BETR SMALLINT,
VTR_SB_PROZ SMALLINT,
VS_STEUER_BETR DECIMAL(14,2),
VS_STEUER_GEM_ZW DECIMAL(14,2),
VERARBEITUNG_ZP TIMESTAMP(6) NOT NULL
)
PRIMARY INDEX( HUB_VERTRAG_HASH_KEY, LOAD_DATE );

select * from T_LVM_MART.SACH_SAT_SACH_VERTRAG_BEIT;